package com.bl4ues.scpclassifieddirective.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import com.bl4ues.scpclassifieddirective.anomalous.Item006BlockItem;
import com.bl4ues.scpclassifieddirective.item.*;
import com.bl4ues.scpclassifieddirective.ScpClassifiedDirectiveMod;

public class ScpClassifiedDirectiveModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ScpClassifiedDirectiveMod.MODID);
	public static final RegistryObject<Item> SAFE_ZONE_TOOL = REGISTRY.register("safe_zone_tool", SafeZoneToolItem::new);
	public static final RegistryObject<Item> ITEM_006 = REGISTRY.register("item_006", () -> new Item006BlockItem(ScpClassifiedDirectiveModBlocks.ITEM_006.get()));
	public static final RegistryObject<Item> BUTTON_ROFF = block(ScpClassifiedDirectiveModBlocks.BUTTON_ROFF);
	public static final RegistryObject<Item> BUTTON_LOFF = block(ScpClassifiedDirectiveModBlocks.BUTTON_LOFF);
	public static final RegistryObject<Item> TESLA_GATE = REGISTRY.register("tesla_gate", () -> new TeslaGateBlockItem(ScpClassifiedDirectiveModBlocks.TESLA_GATE.get()));
	public static final RegistryObject<Item> TESLA_TERMINAL_OFF = block(ScpClassifiedDirectiveModBlocks.TESLA_TERMINAL_OFF);
	public static final RegistryObject<Item> SECURITY_CREDENTIALS = REGISTRY.register("security_credentials", () -> new SecurityCredentialsItem());
	public static final RegistryObject<Item> DECON_OPEN = REGISTRY.register("decon_open", () -> new DecontaminationBlockItem(ScpClassifiedDirectiveModBlocks.DECON_OPEN.get()));
	public static final RegistryObject<Item> SCP_079_SYSTEM_CONTROL = REGISTRY.register("scp_079_system_control", () -> new SystemTerminalItem(ScpClassifiedDirectiveModBlocks.SCP_079_SYSTEM_CONTROL.get()));
	public static final RegistryObject<Item> SCP_079_AUXILIARY_POWER = block(ScpClassifiedDirectiveModBlocks.SCP_079_AUXILIARY_POWER);
	public static final RegistryObject<Item> SCP_079CONTROLOFF = block(ScpClassifiedDirectiveModBlocks.SCP_079CONTROLOFF);
	public static final RegistryObject<Item> SCP_079ON = block(ScpClassifiedDirectiveModBlocks.SCP_079ON);
	public static final RegistryObject<Item> SCP_294 = block(ScpClassifiedDirectiveModBlocks.SCP_294);
	public static final RegistryObject<Item> SCP_330 = block(ScpClassifiedDirectiveModBlocks.SCP_330);
	public static final RegistryObject<Item> SCP_426 = block(ScpClassifiedDirectiveModBlocks.SCP_426);
	public static final RegistryObject<Item> SCP_572 = REGISTRY.register("scp_572", () -> new SCP572Item());
	public static final RegistryObject<Item> SCP_902_CLOSED = REGISTRY.register("scp_902_closed", () -> new Scp902BlockItem(ScpClassifiedDirectiveModBlocks.SCP_902_CLOSED.get(), false));
	public static final RegistryObject<Item> SCP_1176 = REGISTRY.register("scp_1176", () -> new Scp1176BlockItem(ScpClassifiedDirectiveModBlocks.SCP_1176.get()));
	public static final RegistryObject<Item> SCP_330_BLUE_CANDY = REGISTRY.register("scp_330_blue_candy", Scp330CandyItem::new);
	public static final RegistryObject<Item> SCP_330_PINK_CANDY = REGISTRY.register("scp_330_pink_candy", Scp330CandyItem::new);
	public static final RegistryObject<Item> SCP_330_YELLOW_CANDY = REGISTRY.register("scp_330_yellow_candy", Scp330CandyItem::new);
	public static final RegistryObject<Item> SCP_1176HONEY = REGISTRY.register("scp_1176honey", () -> new Scp1176honeyItem());
	public static final RegistryObject<Item> PLAYING_CARD = REGISTRY.register("playing_card", () -> new PlayingCardItem());
	public static final RegistryObject<Item> CREDIT_CARD = REGISTRY.register("credit_card", () -> new CreditCardItem());
	public static final RegistryObject<Item> PIECES_OF_PAPER = REGISTRY.register("pieces_of_paper", () -> new PiecesOfPaperItem());
	public static final RegistryObject<Item> COIN = REGISTRY.register("coin", () -> new CoinItem());
	public static final RegistryObject<Item> EMPTY_CUP = REGISTRY.register("empty_cup", () -> new EmptyCupItem());
	public static final RegistryObject<Item> HAZMAT_SUIT = REGISTRY.register("hazmat_suit", HazmatSuitItem::new);
	public static final RegistryObject<Item> HAZMAT_SUIT_HELMET = REGISTRY.register("hazmat_suit_helmet", () -> new HazmatArmorItem(ArmorItem.Type.HELMET));
	public static final RegistryObject<Item> HAZMAT_SUIT_CHESTPLATE = REGISTRY.register("hazmat_suit_chestplate", () -> new HazmatArmorItem(ArmorItem.Type.CHESTPLATE));
	public static final RegistryObject<Item> HAZMAT_SUIT_LEGGINGS = REGISTRY.register("hazmat_suit_leggings", () -> new HazmatArmorItem(ArmorItem.Type.LEGGINGS));
	public static final RegistryObject<Item> HAZMAT_SUIT_BOOTS = REGISTRY.register("hazmat_suit_boots", () -> new HazmatArmorItem(ArmorItem.Type.BOOTS));
	public static final RegistryObject<Item> LEVEL_1_KEYCARD = REGISTRY.register("level_1_keycard", () -> new Level1KeycardItem());
	public static final RegistryObject<Item> LEVEL_2_KEYCARD = REGISTRY.register("level_2_keycard", () -> new Level2KeycardItem());
	public static final RegistryObject<Item> LEVEL_3_KEYCARD = REGISTRY.register("level_3_keycard", () -> new Level3KeycardItem());
	public static final RegistryObject<Item> LEVEL_4_KEYCARD = REGISTRY.register("level_4_keycard", () -> new Level4KeycardItem());
	public static final RegistryObject<Item> LEVEL_5_KEYCARD = REGISTRY.register("level_5_keycard", () -> new Level5KeycardItem());
	public static final RegistryObject<Item> LEVEL_6_KEYCARD = REGISTRY.register("level_6_keycard", () -> new Level6KeycardItem());
	public static final RegistryObject<Item> RIGHT_READER = block(ScpClassifiedDirectiveModBlocks.RIGHT_READER);
	public static final RegistryObject<Item> LEFT_READER = block(ScpClassifiedDirectiveModBlocks.LEFT_READER);
	public static final RegistryObject<Item> LV_2_RIGHT_READER = block(ScpClassifiedDirectiveModBlocks.LV_2_RIGHT_READER);
	public static final RegistryObject<Item> LV_2_LEFT_READER = block(ScpClassifiedDirectiveModBlocks.LV_2_LEFT_READER);
	public static final RegistryObject<Item> LV_3_RIGHT_READER = block(ScpClassifiedDirectiveModBlocks.LV_3_RIGHT_READER);
	public static final RegistryObject<Item> LV_3_LEFT_READER = block(ScpClassifiedDirectiveModBlocks.LV_3_LEFT_READER);
	public static final RegistryObject<Item> LV_4_RIGHT_READER = block(ScpClassifiedDirectiveModBlocks.LV_4_RIGHT_READER);
	public static final RegistryObject<Item> LV_4_LEFT_READER = block(ScpClassifiedDirectiveModBlocks.LV_4_LEFT_READER);
	public static final RegistryObject<Item> LV_5_RIGHT_READER = block(ScpClassifiedDirectiveModBlocks.LV_5_RIGHT_READER);
	public static final RegistryObject<Item> LV_5_LEFT_READER = block(ScpClassifiedDirectiveModBlocks.LV_5_LEFT_READER);
	public static final RegistryObject<Item> LV_6_RIGHT_READER = block(ScpClassifiedDirectiveModBlocks.LV_6_RIGHT_READER);
	public static final RegistryObject<Item> LV_6_LEFT_READER = block(ScpClassifiedDirectiveModBlocks.LV_6_LEFT_READER);
	public static final RegistryObject<Item> TESLA_ACTIVE = block(ScpClassifiedDirectiveModBlocks.TESLA_ACTIVE);
	public static final RegistryObject<Item> TESLA_RECHARGE = block(ScpClassifiedDirectiveModBlocks.TESLA_RECHARGE);
	public static final RegistryObject<Item> TESLA_ACTIVE_2 = block(ScpClassifiedDirectiveModBlocks.TESLA_ACTIVE_2);
	public static final RegistryObject<Item> TESLA_ACTIVE_3 = block(ScpClassifiedDirectiveModBlocks.TESLA_ACTIVE_3);
	public static final RegistryObject<Item> TESLA_ACTIVE_4 = block(ScpClassifiedDirectiveModBlocks.TESLA_ACTIVE_4);
	public static final RegistryObject<Item> TESLA_TERMINAL_BLOCK = block(ScpClassifiedDirectiveModBlocks.TESLA_TERMINAL_BLOCK);
	public static final RegistryObject<Item> SCP_079OFF = block(ScpClassifiedDirectiveModBlocks.SCP_079OFF);
	public static final RegistryObject<Item> SCP_079CONTROL = block(ScpClassifiedDirectiveModBlocks.SCP_079CONTROL);
	public static final RegistryObject<Item> SCP_902_OPEN = REGISTRY.register("scp_902_open", () -> new Scp902BlockItem(ScpClassifiedDirectiveModBlocks.SCP_902_OPEN.get(), true));
	public static final RegistryObject<Item> BUTTON_RON = block(ScpClassifiedDirectiveModBlocks.BUTTON_RON);
	public static final RegistryObject<Item> BUTTON_LON = block(ScpClassifiedDirectiveModBlocks.BUTTON_LON);
	public static final RegistryObject<Item> DECON_CLOSED = block(ScpClassifiedDirectiveModBlocks.DECON_CLOSED);
	public static final RegistryObject<Item> DECON_OPEN_RELOAD = block(ScpClassifiedDirectiveModBlocks.DECON_OPEN_RELOAD);
	public static final RegistryObject<Item> RIGHT_READER_WRONG = block(ScpClassifiedDirectiveModBlocks.RIGHT_READER_WRONG);
	public static final RegistryObject<Item> RIGHT_READER_ACCEPT = block(ScpClassifiedDirectiveModBlocks.RIGHT_READER_ACCEPT);
	public static final RegistryObject<Item> LEFT_READER_WRONG = block(ScpClassifiedDirectiveModBlocks.LEFT_READER_WRONG);
	public static final RegistryObject<Item> LEFT_READER_ACCEPT = block(ScpClassifiedDirectiveModBlocks.LEFT_READER_ACCEPT);
	public static final RegistryObject<Item> LV_2_RIGHT_READER_WRONG = block(ScpClassifiedDirectiveModBlocks.LV_2_RIGHT_READER_WRONG);
	public static final RegistryObject<Item> LV_2_RIGHT_READER_ACCEPT = block(ScpClassifiedDirectiveModBlocks.LV_2_RIGHT_READER_ACCEPT);
	public static final RegistryObject<Item> LV_2_LEFT_READER_WRONG = block(ScpClassifiedDirectiveModBlocks.LV_2_LEFT_READER_WRONG);
	public static final RegistryObject<Item> LV_2_LEFT_READER_ACCEPT = block(ScpClassifiedDirectiveModBlocks.LV_2_LEFT_READER_ACCEPT);
	public static final RegistryObject<Item> LV_3_RIGHT_READER_WRONG = block(ScpClassifiedDirectiveModBlocks.LV_3_RIGHT_READER_WRONG);
	public static final RegistryObject<Item> LV_3_RIGHT_READER_ACCEPT = block(ScpClassifiedDirectiveModBlocks.LV_3_RIGHT_READER_ACCEPT);
	public static final RegistryObject<Item> LV_3_LEFT_READER_WRONG = block(ScpClassifiedDirectiveModBlocks.LV_3_LEFT_READER_WRONG);
	public static final RegistryObject<Item> LV_3_LEFT_READER_ACCEPT = block(ScpClassifiedDirectiveModBlocks.LV_3_LEFT_READER_ACCEPT);
	public static final RegistryObject<Item> LV_4_RIGHT_READER_WRONG = block(ScpClassifiedDirectiveModBlocks.LV_4_RIGHT_READER_WRONG);
	public static final RegistryObject<Item> LV_4_RIGHT_READER_ACCEPT = block(ScpClassifiedDirectiveModBlocks.LV_4_RIGHT_READER_ACCEPT);
	public static final RegistryObject<Item> LV_4_LEFT_READER_WRONG = block(ScpClassifiedDirectiveModBlocks.LV_4_LEFT_READER_WRONG);
	public static final RegistryObject<Item> LV_4_LEFT_READER_ACCEPT = block(ScpClassifiedDirectiveModBlocks.LV_4_LEFT_READER_ACCEPT);
	public static final RegistryObject<Item> LV_5_RIGHT_READER_WRONG = block(ScpClassifiedDirectiveModBlocks.LV_5_RIGHT_READER_WRONG);
	public static final RegistryObject<Item> LV_5_RIGHT_READER_ACCEPT = block(ScpClassifiedDirectiveModBlocks.LV_5_RIGHT_READER_ACCEPT);
	public static final RegistryObject<Item> LV_5_LEFT_READER_WRONG = block(ScpClassifiedDirectiveModBlocks.LV_5_LEFT_READER_WRONG);
	public static final RegistryObject<Item> LV_5_LEFT_READER_ACCEPT = block(ScpClassifiedDirectiveModBlocks.LV_5_LEFT_READER_ACCEPT);
	public static final RegistryObject<Item> LV_6_RIGHT_READER_WRONG = block(ScpClassifiedDirectiveModBlocks.LV_6_RIGHT_READER_WRONG);
	public static final RegistryObject<Item> LV_6_RIGHT_READER_ACCEPT = block(ScpClassifiedDirectiveModBlocks.LV_6_RIGHT_READER_ACCEPT);
	public static final RegistryObject<Item> LV_6_LEFT_READER_WRONG = block(ScpClassifiedDirectiveModBlocks.LV_6_LEFT_READER_WRONG);
	public static final RegistryObject<Item> LV_6_LEFT_READER_ACCEPT = block(ScpClassifiedDirectiveModBlocks.LV_6_LEFT_READER_ACCEPT);
	public static final RegistryObject<Item> SCP_294_OUT_OF_RANGE = block(ScpClassifiedDirectiveModBlocks.SCP_294_OUT_OF_RANGE);
	public static final RegistryObject<Item> SCP_294_STOCKING = block(ScpClassifiedDirectiveModBlocks.SCP_294_STOCKING);
	public static final RegistryObject<Item> CUP_OF_COFFEE = REGISTRY.register("cup_of_coffee", () -> new CoffeeItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
