package com.bl4ues.scpclassifieddirective.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import com.bl4ues.scpclassifieddirective.block.TeslaTerminalOffBlock;
import com.bl4ues.scpclassifieddirective.block.TeslaTerminalBlockBlock;
import com.bl4ues.scpclassifieddirective.block.TeslaRechargeBlock;
import com.bl4ues.scpclassifieddirective.block.TeslaGateBlock;
import com.bl4ues.scpclassifieddirective.block.TeslaActiveBlock;
import com.bl4ues.scpclassifieddirective.block.TeslaActive4Block;
import com.bl4ues.scpclassifieddirective.block.TeslaActive3Block;
import com.bl4ues.scpclassifieddirective.block.TeslaActive2Block;
import com.bl4ues.scpclassifieddirective.block.Scp902OpenBlock;
import com.bl4ues.scpclassifieddirective.block.Scp902ClosedBlock;
import com.bl4ues.scpclassifieddirective.block.Scp426Block;
import com.bl4ues.scpclassifieddirective.block.Scp330Block;
import com.bl4ues.scpclassifieddirective.block.Scp294StockingBlock;
import com.bl4ues.scpclassifieddirective.block.Scp294OutOfRangeBlock;
import com.bl4ues.scpclassifieddirective.block.Scp294Block;
import com.bl4ues.scpclassifieddirective.block.Scp1176Block;
import com.bl4ues.scpclassifieddirective.block.Scp079onBlock;
import com.bl4ues.scpclassifieddirective.block.Scp079offBlock;
import com.bl4ues.scpclassifieddirective.block.Scp079controloffBlock;
import com.bl4ues.scpclassifieddirective.block.Scp079controlBlock;
import com.bl4ues.scpclassifieddirective.block.SCP079SystemControlBlock;
import com.bl4ues.scpclassifieddirective.block.Scp079AuxiliaryPowerBlock;
import com.bl4ues.scpclassifieddirective.block.RightReaderWrongBlock;
import com.bl4ues.scpclassifieddirective.block.RightReaderBlock;
import com.bl4ues.scpclassifieddirective.block.RightReaderAcceptBlock;
import com.bl4ues.scpclassifieddirective.block.Lv6RightReaderWrongBlock;
import com.bl4ues.scpclassifieddirective.block.Lv6RightReaderBlock;
import com.bl4ues.scpclassifieddirective.block.Lv6RightReaderAcceptBlock;
import com.bl4ues.scpclassifieddirective.block.Lv6LeftReaderWrongBlock;
import com.bl4ues.scpclassifieddirective.block.Lv6LeftReaderBlock;
import com.bl4ues.scpclassifieddirective.block.Lv6LeftReaderAcceptBlock;
import com.bl4ues.scpclassifieddirective.block.Lv5RightReaderWrongBlock;
import com.bl4ues.scpclassifieddirective.block.Lv5RightReaderBlock;
import com.bl4ues.scpclassifieddirective.block.Lv5RightReaderAcceptBlock;
import com.bl4ues.scpclassifieddirective.block.Lv5LeftReaderWrongBlock;
import com.bl4ues.scpclassifieddirective.block.Lv5LeftReaderBlock;
import com.bl4ues.scpclassifieddirective.block.Lv5LeftReaderAcceptBlock;
import com.bl4ues.scpclassifieddirective.block.Lv4RightReaderWrongBlock;
import com.bl4ues.scpclassifieddirective.block.Lv4RightReaderBlock;
import com.bl4ues.scpclassifieddirective.block.Lv4RightReaderAcceptBlock;
import com.bl4ues.scpclassifieddirective.block.Lv4LeftReaderWrongBlock;
import com.bl4ues.scpclassifieddirective.block.Lv4LeftReaderBlock;
import com.bl4ues.scpclassifieddirective.block.Lv4LeftReaderAcceptBlock;
import com.bl4ues.scpclassifieddirective.block.Lv3RightReaderWrongBlock;
import com.bl4ues.scpclassifieddirective.block.Lv3RightReaderBlock;
import com.bl4ues.scpclassifieddirective.block.Lv3RightReaderAcceptBlock;
import com.bl4ues.scpclassifieddirective.block.Lv3LeftReaderWrongBlock;
import com.bl4ues.scpclassifieddirective.block.Lv3LeftReaderBlock;
import com.bl4ues.scpclassifieddirective.block.Lv3LeftReaderAcceptBlock;
import com.bl4ues.scpclassifieddirective.block.Lv2RightReaderWrongBlock;
import com.bl4ues.scpclassifieddirective.block.Lv2RightReaderBlock;
import com.bl4ues.scpclassifieddirective.block.Lv2RightReaderAcceptBlock;
import com.bl4ues.scpclassifieddirective.block.Lv2LeftReaderWrongBlock;
import com.bl4ues.scpclassifieddirective.block.Lv2LeftReaderBlock;
import com.bl4ues.scpclassifieddirective.block.Lv2LeftReaderAcceptBlock;
import com.bl4ues.scpclassifieddirective.block.LeftReaderWrongBlock;
import com.bl4ues.scpclassifieddirective.block.LeftReaderBlock;
import com.bl4ues.scpclassifieddirective.block.LeftReaderAcceptBlock;
import com.bl4ues.scpclassifieddirective.block.DeconOpenReloadBlock;
import com.bl4ues.scpclassifieddirective.block.DeconOpenBlock;
import com.bl4ues.scpclassifieddirective.block.DeconClosedBlock;
import com.bl4ues.scpclassifieddirective.block.ButtonRonBlock;
import com.bl4ues.scpclassifieddirective.block.ButtonRoffBlock;
import com.bl4ues.scpclassifieddirective.block.ButtonLonBlock;
import com.bl4ues.scpclassifieddirective.block.ButtonLoffBlock;
import com.bl4ues.scpclassifieddirective.ScpClassifiedDirectiveMod;

public class ScpClassifiedDirectiveModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, ScpClassifiedDirectiveMod.MODID);
	public static final RegistryObject<Block> BUTTON_ROFF = REGISTRY.register("button_roff", () -> new ButtonRoffBlock());
	public static final RegistryObject<Block> BUTTON_LOFF = REGISTRY.register("button_loff", () -> new ButtonLoffBlock());
	public static final RegistryObject<Block> TESLA_GATE = REGISTRY.register("tesla_gate", () -> new TeslaGateBlock());
	public static final RegistryObject<Block> TESLA_TERMINAL_OFF = REGISTRY.register("tesla_terminal_off", () -> new TeslaTerminalOffBlock());
	public static final RegistryObject<Block> DECON_OPEN = REGISTRY.register("decon_open", () -> new DeconOpenBlock());
	public static final RegistryObject<Block> SCP_079_SYSTEM_CONTROL = REGISTRY.register("scp_079_system_control", () -> new SCP079SystemControlBlock());
	public static final RegistryObject<Block> SCP_079_AUXILIARY_POWER = REGISTRY.register("scp_079_auxiliary_power", Scp079AuxiliaryPowerBlock::new);
	public static final RegistryObject<Block> SCP_079CONTROLOFF = REGISTRY.register("scp_079controloff", () -> new Scp079controloffBlock());
	public static final RegistryObject<Block> SCP_079ON = REGISTRY.register("scp_079on", () -> new Scp079onBlock());
	public static final RegistryObject<Block> SCP_294 = REGISTRY.register("scp_294", () -> new Scp294Block());
	public static final RegistryObject<Block> SCP_330 = REGISTRY.register("scp_330", () -> new Scp330Block());
	public static final RegistryObject<Block> SCP_426 = REGISTRY.register("scp_426", () -> new Scp426Block());
	public static final RegistryObject<Block> SCP_902_CLOSED = REGISTRY.register("scp_902_closed", () -> new Scp902ClosedBlock());
	public static final RegistryObject<Block> SCP_1176 = REGISTRY.register("scp_1176", () -> new Scp1176Block());
	public static final RegistryObject<Block> RIGHT_READER = REGISTRY.register("right_reader", () -> new RightReaderBlock());
	public static final RegistryObject<Block> LEFT_READER = REGISTRY.register("left_reader", () -> new LeftReaderBlock());
	public static final RegistryObject<Block> LV_2_RIGHT_READER = REGISTRY.register("lv_2_right_reader", () -> new Lv2RightReaderBlock());
	public static final RegistryObject<Block> LV_2_LEFT_READER = REGISTRY.register("lv_2_left_reader", () -> new Lv2LeftReaderBlock());
	public static final RegistryObject<Block> LV_3_RIGHT_READER = REGISTRY.register("lv_3_right_reader", () -> new Lv3RightReaderBlock());
	public static final RegistryObject<Block> LV_3_LEFT_READER = REGISTRY.register("lv_3_left_reader", () -> new Lv3LeftReaderBlock());
	public static final RegistryObject<Block> LV_4_RIGHT_READER = REGISTRY.register("lv_4_right_reader", () -> new Lv4RightReaderBlock());
	public static final RegistryObject<Block> LV_4_LEFT_READER = REGISTRY.register("lv_4_left_reader", () -> new Lv4LeftReaderBlock());
	public static final RegistryObject<Block> LV_5_RIGHT_READER = REGISTRY.register("lv_5_right_reader", () -> new Lv5RightReaderBlock());
	public static final RegistryObject<Block> LV_5_LEFT_READER = REGISTRY.register("lv_5_left_reader", () -> new Lv5LeftReaderBlock());
	public static final RegistryObject<Block> LV_6_RIGHT_READER = REGISTRY.register("lv_6_right_reader", () -> new Lv6RightReaderBlock());
	public static final RegistryObject<Block> LV_6_LEFT_READER = REGISTRY.register("lv_6_left_reader", () -> new Lv6LeftReaderBlock());
	public static final RegistryObject<Block> TESLA_ACTIVE = REGISTRY.register("tesla_active", () -> new TeslaActiveBlock());
	public static final RegistryObject<Block> TESLA_RECHARGE = REGISTRY.register("tesla_recharge", () -> new TeslaRechargeBlock());
	public static final RegistryObject<Block> TESLA_ACTIVE_2 = REGISTRY.register("tesla_active_2", () -> new TeslaActive2Block());
	public static final RegistryObject<Block> TESLA_ACTIVE_3 = REGISTRY.register("tesla_active_3", () -> new TeslaActive3Block());
	public static final RegistryObject<Block> TESLA_ACTIVE_4 = REGISTRY.register("tesla_active_4", () -> new TeslaActive4Block());
	public static final RegistryObject<Block> TESLA_TERMINAL_BLOCK = REGISTRY.register("tesla_terminal_block", () -> new TeslaTerminalBlockBlock());
	public static final RegistryObject<Block> SCP_079OFF = REGISTRY.register("scp_079off", () -> new Scp079offBlock());
	public static final RegistryObject<Block> SCP_079CONTROL = REGISTRY.register("scp_079control", () -> new Scp079controlBlock());
	public static final RegistryObject<Block> SCP_902_OPEN = REGISTRY.register("scp_902_open", () -> new Scp902OpenBlock());
	public static final RegistryObject<Block> BUTTON_RON = REGISTRY.register("button_ron", () -> new ButtonRonBlock());
	public static final RegistryObject<Block> BUTTON_LON = REGISTRY.register("button_lon", () -> new ButtonLonBlock());
	public static final RegistryObject<Block> DECON_CLOSED = REGISTRY.register("decon_closed", () -> new DeconClosedBlock());
	public static final RegistryObject<Block> DECON_OPEN_RELOAD = REGISTRY.register("decon_open_reload", () -> new DeconOpenReloadBlock());
	public static final RegistryObject<Block> RIGHT_READER_WRONG = REGISTRY.register("right_reader_wrong", () -> new RightReaderWrongBlock());
	public static final RegistryObject<Block> RIGHT_READER_ACCEPT = REGISTRY.register("right_reader_accept", () -> new RightReaderAcceptBlock());
	public static final RegistryObject<Block> LEFT_READER_WRONG = REGISTRY.register("left_reader_wrong", () -> new LeftReaderWrongBlock());
	public static final RegistryObject<Block> LEFT_READER_ACCEPT = REGISTRY.register("left_reader_accept", () -> new LeftReaderAcceptBlock());
	public static final RegistryObject<Block> LV_2_RIGHT_READER_WRONG = REGISTRY.register("lv_2_right_reader_wrong", () -> new Lv2RightReaderWrongBlock());
	public static final RegistryObject<Block> LV_2_RIGHT_READER_ACCEPT = REGISTRY.register("lv_2_right_reader_accept", () -> new Lv2RightReaderAcceptBlock());
	public static final RegistryObject<Block> LV_2_LEFT_READER_WRONG = REGISTRY.register("lv_2_left_reader_wrong", () -> new Lv2LeftReaderWrongBlock());
	public static final RegistryObject<Block> LV_2_LEFT_READER_ACCEPT = REGISTRY.register("lv_2_left_reader_accept", () -> new Lv2LeftReaderAcceptBlock());
	public static final RegistryObject<Block> LV_3_RIGHT_READER_WRONG = REGISTRY.register("lv_3_right_reader_wrong", () -> new Lv3RightReaderWrongBlock());
	public static final RegistryObject<Block> LV_3_RIGHT_READER_ACCEPT = REGISTRY.register("lv_3_right_reader_accept", () -> new Lv3RightReaderAcceptBlock());
	public static final RegistryObject<Block> LV_3_LEFT_READER_WRONG = REGISTRY.register("lv_3_left_reader_wrong", () -> new Lv3LeftReaderWrongBlock());
	public static final RegistryObject<Block> LV_3_LEFT_READER_ACCEPT = REGISTRY.register("lv_3_left_reader_accept", () -> new Lv3LeftReaderAcceptBlock());
	public static final RegistryObject<Block> LV_4_RIGHT_READER_WRONG = REGISTRY.register("lv_4_right_reader_wrong", () -> new Lv4RightReaderWrongBlock());
	public static final RegistryObject<Block> LV_4_RIGHT_READER_ACCEPT = REGISTRY.register("lv_4_right_reader_accept", () -> new Lv4RightReaderAcceptBlock());
	public static final RegistryObject<Block> LV_4_LEFT_READER_WRONG = REGISTRY.register("lv_4_left_reader_wrong", () -> new Lv4LeftReaderWrongBlock());
	public static final RegistryObject<Block> LV_4_LEFT_READER_ACCEPT = REGISTRY.register("lv_4_left_reader_accept", () -> new Lv4LeftReaderAcceptBlock());
	public static final RegistryObject<Block> LV_5_RIGHT_READER_WRONG = REGISTRY.register("lv_5_right_reader_wrong", () -> new Lv5RightReaderWrongBlock());
	public static final RegistryObject<Block> LV_5_RIGHT_READER_ACCEPT = REGISTRY.register("lv_5_right_reader_accept", () -> new Lv5RightReaderAcceptBlock());
	public static final RegistryObject<Block> LV_5_LEFT_READER_WRONG = REGISTRY.register("lv_5_left_reader_wrong", () -> new Lv5LeftReaderWrongBlock());
	public static final RegistryObject<Block> LV_5_LEFT_READER_ACCEPT = REGISTRY.register("lv_5_left_reader_accept", () -> new Lv5LeftReaderAcceptBlock());
	public static final RegistryObject<Block> LV_6_RIGHT_READER_WRONG = REGISTRY.register("lv_6_right_reader_wrong", () -> new Lv6RightReaderWrongBlock());
	public static final RegistryObject<Block> LV_6_RIGHT_READER_ACCEPT = REGISTRY.register("lv_6_right_reader_accept", () -> new Lv6RightReaderAcceptBlock());
	public static final RegistryObject<Block> LV_6_LEFT_READER_WRONG = REGISTRY.register("lv_6_left_reader_wrong", () -> new Lv6LeftReaderWrongBlock());
	public static final RegistryObject<Block> LV_6_LEFT_READER_ACCEPT = REGISTRY.register("lv_6_left_reader_accept", () -> new Lv6LeftReaderAcceptBlock());
	public static final RegistryObject<Block> SCP_294_OUT_OF_RANGE = REGISTRY.register("scp_294_out_of_range", () -> new Scp294OutOfRangeBlock());
	public static final RegistryObject<Block> SCP_294_STOCKING = REGISTRY.register("scp_294_stocking", () -> new Scp294StockingBlock());
}