modLoader="javafml"
loaderVersion="[47,)"
license="Creative Commons Sharealike 3.0"

[[mods]]
modId="scp_additions"
version="2.0.1"
displayName="SCP Additions"
authors="Bl4ues"

[[dependencies.scp_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.scp_additions]]
    modId="kleiders_custom_renderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
