modLoader="javafml"
loaderVersion="[47,)"
license="Creative Commons Sharealike 3.0"

[[mods]]
modId="scp_additions"
version="1.0.9"
displayName="SCP Additions"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Bl4ues, MCreator"

[[dependencies.scp_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.scp_additions]]
    modId="kleiders_custom_renderer"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scp_additions]]
    modId="kleiders_custom_renderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

