modLoader="javafml"
loaderVersion="[47,)"
license="Creative Commons Attribution-ShareAlike 3.0"

[[mods]]
modId="scp_additions"
version="${mod_version}"
displayName="SCP Additions"
authors="Bl4ues"
logoFile="logo.png"
description='''
SCP Additions is an SCP survival horror and facility-building mod for Minecraft 1.20.1. Inspired by SCP: Containment Breach and SCP Unity, it combines functional SCPs and containment machinery with a custom inventory, survival systems, keycard security, animated doors, and a large collection of facility-building content.
'''

[[dependencies.scp_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.scp_additions]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scp_additions]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.4.9,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.scp_additions]]
    modId="kleiders_custom_renderer"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="CLIENT"


[[dependencies.scp_additions]]
    modId="moremcmeta_emissive_plugin"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="CLIENT"
