modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Bl4ues"
logoFile="logo.png"
description='''
SCP Additions is an SCP survival horror and facility-building mod for Minecraft 1.21.1. Inspired by SCP: Containment Breach and SCP Unity, it combines functional SCPs and containment machinery with a custom inventory, survival systems, keycard security, animated doors, and a large collection of facility-building content.
'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
versionRange="[4.9.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kleiders_custom_renderer"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="moremcmeta_emissive_plugin"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
