modLoader="javafml"
loaderVersion="[1,)"
license="Creative Commons Attribution-ShareAlike 3.0"
issueTrackerURL="https://github.com/Bl4ues/SCP-Additions/issues"

[[mods]]
modId="scp_additions"
version="${mod_version}"
displayName="SCP Additions"
authors="Bl4ues"
logoFile="logo.png"
displayURL="https://github.com/Bl4ues/SCP-Additions"
description='''
SCP Additions is an SCP survival horror and facility-building mod for Minecraft 1.21.1. Inspired by SCP: Containment Breach and SCP Unity, it combines functional SCPs and containment machinery with a custom inventory, survival systems, keycard security, animated doors, and a large collection of facility-building content.
'''

[[dependencies.scp_additions]]
modId="neoforge"
type="required"
versionRange="[21.1.235,)"
ordering="NONE"
side="BOTH"

[[dependencies.scp_additions]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.scp_additions]]
modId="geckolib"
type="required"
versionRange="[4.9.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.scp_additions]]
modId="kleiders_custom_renderer"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.scp_additions]]
modId="moremcmeta_emissive_plugin"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
