package net.mcreator.scpadditions.init;

import java.util.function.Supplier;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.neoforged.neoforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.scpadditions.item.*;
import net.mcreator.scpadditions.ScpAdditionsMod;

public class ScpAdditionsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(BuiltInRegistries.ITEM, ScpAdditionsMod.MODID);
	public static final Supplier<Item> BUTTON_ROFF = block(ScpAdditionsModBlocks.BUTTON_ROFF);
	public static final Supplier<Item> BUTTON_LOFF = block(ScpAdditionsModBlocks.BUTTON_LOFF);
	public static final Supplier<Item> TESLA_GATE = block(ScpAdditionsModBlocks.TESLA_GATE);
	public static final Supplier<Item> TESLA_TERMINAL_OFF = block(ScpAdditionsModBlocks.TESLA_TERMINAL_OFF);
	public static final Supplier<Item> SECURITY_CREDENTIALS = REGISTRY.register("security_credentials", () -> new SecurityCredentialsItem());
	public static final Supplier<Item> DECON_OPEN = block(ScpAdditionsModBlocks.DECON_OPEN);
	public static final Supplier<Item> SCP_079_SYSTEM_CONTROL = block(ScpAdditionsModBlocks.SCP_079_SYSTEM_CONTROL);
	public static final Supplier<Item> SCP_079CONTROLOFF = block(ScpAdditionsModBlocks.SCP_079CONTROLOFF);
	public static final Supplier<Item> SCP_079ON = block(ScpAdditionsModBlocks.SCP_079ON);
	public static final Supplier<Item> SCP_294 = block(ScpAdditionsModBlocks.SCP_294);
	public static final Supplier<Item> SCP_330 = block(ScpAdditionsModBlocks.SCP_330);
	public static final Supplier<Item> SCP_426 = block(ScpAdditionsModBlocks.SCP_426);
	public static final Supplier<Item> SCP_572 = REGISTRY.register("scp_572", () -> new SCP572Item());
	public static final Supplier<Item> SCP_902_CLOSED = block(ScpAdditionsModBlocks.SCP_902_CLOSED);
	public static final Supplier<Item> SCP_914BLOCK = block(ScpAdditionsModBlocks.SCP_914BLOCK);
	public static final Supplier<Item> SCP_914CLOCKWORKS = block(ScpAdditionsModBlocks.SCP_914CLOCKWORKS);
	public static final Supplier<Item> SCP_914BODY = block(ScpAdditionsModBlocks.SCP_914BODY);
	public static final Supplier<Item> SCP_914DIAL_1TO_1 = block(ScpAdditionsModBlocks.SCP_914DIAL_1TO_1);
	public static final Supplier<Item> SCP_914_KEY_WIND = block(ScpAdditionsModBlocks.SCP_914_KEY_WIND);
	public static final Supplier<Item> SCP_914_INTAKE = block(ScpAdditionsModBlocks.SCP_914_INTAKE);
	public static final Supplier<Item> SCP_914_OUTPUT = block(ScpAdditionsModBlocks.SCP_914_OUTPUT);
	public static final Supplier<Item> SCP_914_INTAKE_DOOR = block(ScpAdditionsModBlocks.SCP_914_INTAKE_DOOR);
	public static final Supplier<Item> SCP_914_OUTPUT_DOOR = block(ScpAdditionsModBlocks.SCP_914_OUTPUT_DOOR);
	public static final Supplier<Item> SCP_914_ASSEMBLY_KIT = REGISTRY.register("scp_914_assembly_kit", () -> new Scp914AssemblyKitItem());
	public static final Supplier<Item> SCP_1176 = block(ScpAdditionsModBlocks.SCP_1176);
	public static final Supplier<Item> SCP_330_RED_CANDY = REGISTRY.register("scp_330_red_candy", () -> new Scp330RedCandyItem());
	public static final Supplier<Item> SCP_330_GREEN_CANDY = REGISTRY.register("scp_330_green_candy", () -> new Scp330GreenCandyItem());
	public static final Supplier<Item> SCP_330_YELLOW_CANDY = REGISTRY.register("scp_330_yellow_candy", () -> new Scp330YellowCandyItem());
	public static final Supplier<Item> SCP_330_BLUE_CANDY = REGISTRY.register("scp_330_blue_candy", () -> new Scp330BlueCandyItem());
	public static final Supplier<Item> SCP_1176HONEY = REGISTRY.register("scp_1176honey", () -> new Scp1176honeyItem());
	public static final Supplier<Item> PLAYING_CARD = REGISTRY.register("playing_card", () -> new PlayingCardItem());
	public static final Supplier<Item> CREDIT_CARD = REGISTRY.register("credit_card", () -> new CreditCardItem());
	public static final Supplier<Item> PIECES_OF_PAPER = REGISTRY.register("pieces_of_paper", () -> new PiecesOfPaperItem());
	public static final Supplier<Item> COIN = REGISTRY.register("coin", () -> new CoinItem());
	public static final Supplier<Item> EMPTY_CUP = REGISTRY.register("empty_cup", () -> new EmptyCupItem());
	public static final Supplier<Item> HAZMAT_SUIT = REGISTRY.register("hazmat_suit", HazmatSuitItem::new);
	public static final Supplier<Item> HAZMAT_SUIT_HELMET = REGISTRY.register("hazmat_suit_helmet", () -> new HazmatArmorItem(ArmorItem.Type.HELMET));
	public static final Supplier<Item> HAZMAT_SUIT_CHESTPLATE = REGISTRY.register("hazmat_suit_chestplate", () -> new HazmatArmorItem(ArmorItem.Type.CHESTPLATE));
	public static final Supplier<Item> HAZMAT_SUIT_LEGGINGS = REGISTRY.register("hazmat_suit_leggings", () -> new HazmatArmorItem(ArmorItem.Type.LEGGINGS));
	public static final Supplier<Item> HAZMAT_SUIT_BOOTS = REGISTRY.register("hazmat_suit_boots", () -> new HazmatArmorItem(ArmorItem.Type.BOOTS));
	public static final Supplier<Item> LEVEL_1_KEYCARD = REGISTRY.register("level_1_keycard", () -> new Level1KeycardItem());
	public static final Supplier<Item> LEVEL_2_KEYCARD = REGISTRY.register("level_2_keycard", () -> new Level2KeycardItem());
	public static final Supplier<Item> LEVEL_3_KEYCARD = REGISTRY.register("level_3_keycard", () -> new Level3KeycardItem());
	public static final Supplier<Item> LEVEL_4_KEYCARD = REGISTRY.register("level_4_keycard", () -> new Level4KeycardItem());
	public static final Supplier<Item> LEVEL_5_KEYCARD = REGISTRY.register("level_5_keycard", () -> new Level5KeycardItem());
	public static final Supplier<Item> LEVEL_6_KEYCARD = REGISTRY.register("level_6_keycard", () -> new Level6KeycardItem());
	public static final Supplier<Item> RIGHT_READER = block(ScpAdditionsModBlocks.RIGHT_READER);
	public static final Supplier<Item> LEFT_READER = block(ScpAdditionsModBlocks.LEFT_READER);
	public static final Supplier<Item> LV_2_RIGHT_READER = block(ScpAdditionsModBlocks.LV_2_RIGHT_READER);
	public static final Supplier<Item> LV_2_LEFT_READER = block(ScpAdditionsModBlocks.LV_2_LEFT_READER);
	public static final Supplier<Item> LV_3_RIGHT_READER = block(ScpAdditionsModBlocks.LV_3_RIGHT_READER);
	public static final Supplier<Item> LV_3_LEFT_READER = block(ScpAdditionsModBlocks.LV_3_LEFT_READER);
	public static final Supplier<Item> LV_4_RIGHT_READER = block(ScpAdditionsModBlocks.LV_4_RIGHT_READER);
	public static final Supplier<Item> LV_4_LEFT_READER = block(ScpAdditionsModBlocks.LV_4_LEFT_READER);
	public static final Supplier<Item> LV_5_RIGHT_READER = block(ScpAdditionsModBlocks.LV_5_RIGHT_READER);
	public static final Supplier<Item> LV_5_LEFT_READER = block(ScpAdditionsModBlocks.LV_5_LEFT_READER);
	public static final Supplier<Item> LV_6_RIGHT_READER = block(ScpAdditionsModBlocks.LV_6_RIGHT_READER);
	public static final Supplier<Item> LV_6_LEFT_READER = block(ScpAdditionsModBlocks.LV_6_LEFT_READER);
	public static final Supplier<Item> TESLA_ACTIVE = block(ScpAdditionsModBlocks.TESLA_ACTIVE);
	public static final Supplier<Item> TESLA_RECHARGE = block(ScpAdditionsModBlocks.TESLA_RECHARGE);
	public static final Supplier<Item> TESLA_ACTIVE_2 = block(ScpAdditionsModBlocks.TESLA_ACTIVE_2);
	public static final Supplier<Item> TESLA_ACTIVE_3 = block(ScpAdditionsModBlocks.TESLA_ACTIVE_3);
	public static final Supplier<Item> TESLA_ACTIVE_4 = block(ScpAdditionsModBlocks.TESLA_ACTIVE_4);
	public static final Supplier<Item> TESLA_TERMINAL_BLOCK = block(ScpAdditionsModBlocks.TESLA_TERMINAL_BLOCK);
	public static final Supplier<Item> SCP_079OFF = block(ScpAdditionsModBlocks.SCP_079OFF);
	public static final Supplier<Item> SCP_079CONTROL = block(ScpAdditionsModBlocks.SCP_079CONTROL);
	public static final Supplier<Item> SCP_902_OPEN = block(ScpAdditionsModBlocks.SCP_902_OPEN);
	public static final Supplier<Item> BUTTON_RON = block(ScpAdditionsModBlocks.BUTTON_RON);
	public static final Supplier<Item> BUTTON_LON = block(ScpAdditionsModBlocks.BUTTON_LON);
	public static final Supplier<Item> SCP_914DIAL_ROUGH = block(ScpAdditionsModBlocks.SCP_914DIAL_ROUGH);
	public static final Supplier<Item> SCP_914DIAL_COARSE = block(ScpAdditionsModBlocks.SCP_914DIAL_COARSE);
	public static final Supplier<Item> SCP_914DIAL_FINE = block(ScpAdditionsModBlocks.SCP_914DIAL_FINE);
	public static final Supplier<Item> SCP_914DIAL_VERY_FINE = block(ScpAdditionsModBlocks.SCP_914DIAL_VERY_FINE);
	public static final Supplier<Item> SCP_914CLOCKWORKS_2 = block(ScpAdditionsModBlocks.SCP_914CLOCKWORKS_2);
	public static final Supplier<Item> SCP_914_OUTPUT_DOOR_CLOSED = block(ScpAdditionsModBlocks.SCP_914_OUTPUT_DOOR_CLOSED);
	public static final Supplier<Item> SCP_914_INTAKE_DOOR_CLOSED = block(ScpAdditionsModBlocks.SCP_914_INTAKE_DOOR_CLOSED);
	public static final Supplier<Item> DECON_CLOSED = block(ScpAdditionsModBlocks.DECON_CLOSED);
	public static final Supplier<Item> DECON_OPEN_RELOAD = block(ScpAdditionsModBlocks.DECON_OPEN_RELOAD);
	public static final Supplier<Item> RIGHT_READER_WRONG = block(ScpAdditionsModBlocks.RIGHT_READER_WRONG);
	public static final Supplier<Item> RIGHT_READER_ACCEPT = block(ScpAdditionsModBlocks.RIGHT_READER_ACCEPT);
	public static final Supplier<Item> LEFT_READER_WRONG = block(ScpAdditionsModBlocks.LEFT_READER_WRONG);
	public static final Supplier<Item> LEFT_READER_ACCEPT = block(ScpAdditionsModBlocks.LEFT_READER_ACCEPT);
	public static final Supplier<Item> LV_2_RIGHT_READER_WRONG = block(ScpAdditionsModBlocks.LV_2_RIGHT_READER_WRONG);
	public static final Supplier<Item> LV_2_RIGHT_READER_ACCEPT = block(ScpAdditionsModBlocks.LV_2_RIGHT_READER_ACCEPT);
	public static final Supplier<Item> LV_2_LEFT_READER_WRONG = block(ScpAdditionsModBlocks.LV_2_LEFT_READER_WRONG);
	public static final Supplier<Item> LV_2_LEFT_READER_ACCEPT = block(ScpAdditionsModBlocks.LV_2_LEFT_READER_ACCEPT);
	public static final Supplier<Item> LV_3_RIGHT_READER_WRONG = block(ScpAdditionsModBlocks.LV_3_RIGHT_READER_WRONG);
	public static final Supplier<Item> LV_3_RIGHT_READER_ACCEPT = block(ScpAdditionsModBlocks.LV_3_RIGHT_READER_ACCEPT);
	public static final Supplier<Item> LV_3_LEFT_READER_WRONG = block(ScpAdditionsModBlocks.LV_3_LEFT_READER_WRONG);
	public static final Supplier<Item> LV_3_LEFT_READER_ACCEPT = block(ScpAdditionsModBlocks.LV_3_LEFT_READER_ACCEPT);
	public static final Supplier<Item> LV_4_RIGHT_READER_WRONG = block(ScpAdditionsModBlocks.LV_4_RIGHT_READER_WRONG);
	public static final Supplier<Item> LV_4_RIGHT_READER_ACCEPT = block(ScpAdditionsModBlocks.LV_4_RIGHT_READER_ACCEPT);
	public static final Supplier<Item> LV_4_LEFT_READER_WRONG = block(ScpAdditionsModBlocks.LV_4_LEFT_READER_WRONG);
	public static final Supplier<Item> LV_4_LEFT_READER_ACCEPT = block(ScpAdditionsModBlocks.LV_4_LEFT_READER_ACCEPT);
	public static final Supplier<Item> LV_5_RIGHT_READER_WRONG = block(ScpAdditionsModBlocks.LV_5_RIGHT_READER_WRONG);
	public static final Supplier<Item> LV_5_RIGHT_READER_ACCEPT = block(ScpAdditionsModBlocks.LV_5_RIGHT_READER_ACCEPT);
	public static final Supplier<Item> LV_5_LEFT_READER_WRONG = block(ScpAdditionsModBlocks.LV_5_LEFT_READER_WRONG);
	public static final Supplier<Item> LV_5_LEFT_READER_ACCEPT = block(ScpAdditionsModBlocks.LV_5_LEFT_READER_ACCEPT);
	public static final Supplier<Item> LV_6_RIGHT_READER_WRONG = block(ScpAdditionsModBlocks.LV_6_RIGHT_READER_WRONG);
	public static final Supplier<Item> LV_6_RIGHT_READER_ACCEPT = block(ScpAdditionsModBlocks.LV_6_RIGHT_READER_ACCEPT);
	public static final Supplier<Item> LV_6_LEFT_READER_WRONG = block(ScpAdditionsModBlocks.LV_6_LEFT_READER_WRONG);
	public static final Supplier<Item> LV_6_LEFT_READER_ACCEPT = block(ScpAdditionsModBlocks.LV_6_LEFT_READER_ACCEPT);
	public static final Supplier<Item> SCP_294_OUT_OF_RANGE = block(ScpAdditionsModBlocks.SCP_294_OUT_OF_RANGE);
	public static final Supplier<Item> SCP_294_STOCKING = block(ScpAdditionsModBlocks.SCP_294_STOCKING);
	public static final Supplier<Item> CUP_OF_COFFEE = REGISTRY.register("cup_of_coffee", () -> new CoffeeItem());

	private static Supplier<Item> block(Supplier<Block> block) {
		return REGISTRY.register(BuiltInRegistries.BLOCK.getKey(block.get()).getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
